# 학습 목표

- TensorFlow 2.0 간단 사용법

In [3]:
import numpy as np
import tensorflow as tf

# Tensor 생성

- []
    - List 생성

In [4]:
[1,2,3]

[1, 2, 3]

In [5]:
[[1,2,3],[4,5,6]]

[[1, 2, 3], [4, 5, 6]]

### Array 생성

- tuple이나 list 둘 다 np.array()로 씌어서 array를 만들 수 있음

In [6]:
arr = np.array([1,2,3])

In [7]:
arr.shape

(3,)

In [8]:
arr = np.array([[1,2,3],[4,5,6]])

In [9]:
arr.shape

(2, 3)

### Tensor 생성

- tf.constant()
    - list -> Tensor

In [10]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

- tf.constant()
    - tuple -> Tensor

In [11]:
tf.constant(((1,2,3),(4,5,6)))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

- tf.constant()
    - Array -> Tensor

In [12]:
arr = np.array([1,2,3])

In [13]:
tensor = tf.constant(arr)
tensor


<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

### Tensor에 담긴 정보 확인

- shape 확인

In [14]:
tensor.shape

TensorShape([3])

- data type 확인
    - 주의: Tensor 생성 할 때도 data type을 정해주지 않기 때문에 data type에 대한 혼동이 올 수 있음
    - Data Type에 따라 모델의 무게나 성능 차이에도 영향을 줄 수 있음

In [15]:
tensor.dtype

tf.int64

- data type 정의

In [16]:
tensor = tf.constant([1,2,3], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

- data type 변환
    - Numpy에서 astype()을 주었듯이, TensorFlow에서는 tf.cast를 사용

In [17]:
tf.cast(tensor, dtype=tf.uint8)

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

- Tensor에서 Numpy 불러오기
    - .numpy()

In [18]:
tensor.numpy()

array([1., 2., 3.], dtype=float32)

- Tensor에서 Numpy 불러오기
    - np.array()

In [22]:
np.array(tensor)

array([1., 2., 3.], dtype=float32)

type()를 사용하여 numpy array로 변환된 것 확인

In [23]:
type(tensor)

tensorflow.python.framework.ops.EagerTensor

In [24]:
type(tensor.numpy())

numpy.ndarray

## 난수 생성

![image.png](attachment:image.png)

- Normal Distribution은 중심극한 이론에 의한 연속적인 모양   
- Uniform Distribution은 중심 극한 이론과는 무관하며 불연속적이며 일정한 분포

- numpy에서는 normal distribution을 기본적으로 생성
    - np.random.randn()

In [19]:
np.random.randn(9)

array([ 1.1574305 , -0.75176291,  0.06148397,  2.29594579, -1.4134364 ,
       -0.25221544,  0.28678027, -1.44336104, -0.06622869])

- tf.random.normal
    - TensorFlow에서 Normal Distribution

In [20]:
tf.random.normal([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.5211507 ,  1.3257143 ,  1.5183275 ],
       [-1.2821234 ,  2.3091424 ,  0.4495921 ],
       [-0.63997054, -0.97778577, -1.9077669 ]], dtype=float32)>

- tf.random.uniform
    - TensorFlow에서 Uniform Distribution

In [21]:
tf.random.uniform([4,4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.9259653 , 0.6479056 , 0.5685812 , 0.7911737 ],
       [0.8304839 , 0.67716646, 0.27734947, 0.4015795 ],
       [0.5865394 , 0.08203554, 0.14047122, 0.9682572 ],
       [0.30368567, 0.54643   , 0.20865321, 0.86724293]], dtype=float32)>